examples = {
	"Relay Radio clearErrors"					:"OK",
	"Relay Radio getLastError"					:"All good; No errors!",
	"Relay Radio getErrorCount"					:"0",
	"Relay Radio getSignalStrength"				:"97%",
	"Relay Radio getTemperature"				:"33C",
	"Relay System ping"							:"pong",
	"Relay System getVersion"					:"V1.1",
	"Relay System getAvailableMemory"			:"2457",
	"Robot Radio clearErrors"					:"OK",
	"Robot Radio getLastError"					:"All good; No errors!",
	"Robot Radio getErrorCount"					:"0",
	"Robot Radio getSignalStrength"				:"97%",
	"Robot Radio getTemperature"				:"33C",
	"Robot Audio clearErrors"					:"OK",
	"Robot Audio getLastError"					:"All good; No errors!",
	"Robot Audio getErrorCount"					:"0",
	"Robot Audio beep"							:"OK",
	"Robot Audio setVolume 55%"					:"OK",
	"Robot Audio getVolume"						:"70%",
	"Robot Audio play track001.mp3"				:"OK",
	"Robot Audio isPlaying"						:"True",
	"Robot Audio pause"							:"OK",
	"Robot Audio resume"						:"OK",
	"Robot Audio isPaused"						:"True",
	"Robot Audio stop"							:"OK",
	"Robot Audio isStopped"						:"True",
	"Robot Audio getLastFileName"				:"track001.mp3",
	"Robot GPS clearErrors"						:"OK",
	"Robot GPS getLastError"					:"All good; No errors!",
	"Robot GPS getErrorCount"					:"0",
	"Robot GPS getLocation"						:"Waiting for fix",
	"Robot GPS getAltitude"						:"Waiting for fix",
	"Robot GPS getTime"							:"00:42:17.000 UTC",
	"Robot GPS getDate"							:"2018-11-5",
	"Robot GPS getFix"							:"Bad fix",
	"Robot GPS getSatelliteCount"				:"0",
	"Robot Servo clearErrors"					:"OK",
	"Robot Servo getLastError"					:"All good; No errors!",
	"Robot Servo getErrorCount"					:"0",
	"Robot Servo getVoltage"					:"5.89V",
	"Robot Servo 0 getAngle"					:45,
	"Robot Servo 0 setAngle 45"					:"OK",
	"Robot Servo 0 goLimp"						:"OK",
	"Robot Servo 1 getAngle"					:45,
	"Robot Servo 1 setAngle 45"					:"OK",
	"Robot Servo 1 goLimp"						:"OK",
	"Robot Servo 2 getAngle"					:45,
	"Robot Servo 2 setAngle 45"					:"OK",
	"Robot Servo 2 goLimp"						:"OK",
	"Robot Servo 3 getAngle"					:45,
	"Robot Servo 3 setAngle 45"					:"OK",
	"Robot Servo 3 goLimp"						:"OK",
	"Robot Servo 4 getAngle"					:45,
	"Robot Servo 4 setAngle 45"					:"OK",
	"Robot Servo 4 goLimp"						:"OK",
	"Robot Servo 5 getAngle"					:45,
	"Robot Servo 5 setAngle 45"					:"OK",
	"Robot Servo 5 goLimp"						:"OK",
	"Robot Servo 6 getAngle"					:45,
	"Robot Servo 6 setAngle 45"					:"OK",
	"Robot Servo 6 goLimp"						:"OK",
	"Robot Servo 7 getAngle"					:45,
	"Robot Servo 7 setAngle 45"					:"OK",
	"Robot Servo 7 goLimp"						:"OK",
	"Robot Display clearErrors"					:"OK",
	"Robot Display getLastError"				:"All good; No errors!",
	"Robot Display getErrorCount"				:"0",
	"Robot Display getUpdateCount"				:"1242",
	"Robot Display show all"					:"OK",
	"Robot Display show title"					:"OK",
	"Robot Display show loopCount"				:"OK",
	"Robot Display show commandCount"			:"OK",
	"Robot Display show totalErrorCount"		:"OK",
	"Robot Display show line0"					:"OK",
	"Robot Display show line1"					:"OK",
	"Robot Display show line2"					:"OK",
	"Robot Display show line3"					:"OK",
	"Robot Display show signal"					:"OK",
	"Robot Display show battery"				:"OK",
	"Robot Display show volume"					:"OK",
	"Robot Display show timeout"				:"OK",
	"Robot Display hide all"					:"OK",
	"Robot Display hide title"					:"OK",
	"Robot Display hide loopCount"				:"OK",
	"Robot Display hide commandCount"			:"OK",
	"Robot Display hide totalErrorCount"		:"OK",
	"Robot Display hide line0"					:"OK",
	"Robot Display hide line1"					:"OK",
	"Robot Display hide line2"					:"OK",
	"Robot Display hide line3"					:"OK",
	"Robot Display hide signal"					:"OK",
	"Robot Display hide battery"				:"OK",
	"Robot Display hide volume"					:"OK",
	"Robot Display hide timeout"				:"OK",
	"Robot Display isShowing title"				:"true",
	"Robot Display isShowing loopCount"			:"true",
	"Robot Display isShowing commandCount"		:"true",
	"Robot Display isShowing totalErrorCount"	:"true",
	"Robot Display isShowing line0"				:"true",
	"Robot Display isShowing line1"				:"true",
	"Robot Display isShowing line2"				:"true",
	"Robot Display isShowing line3"				:"true",
	"Robot Display isShowing signal"			:"true",
	"Robot Display isShowing battery"			:"true",
	"Robot Display isShowing volume"			:"true",
	"Robot Display isShowing timeout"			:"true",
	"Robot Display setText line0 test text"		:"OK",
	"Robot Display setText line1 test text"		:"OK",
	"Robot Display setText line2 test text"		:"OK",
	"Robot Display setText line3 test text"		:"OK",
	"Robot Display getText line0"				:"Line0 text here",
	"Robot Display getText line1"				:"Line1 text here",
	"Robot Display getText line2"				:"Line2 text here",
	"Robot Display getText line3"				:"Line3 text here",
	"Robot Battery clearErrors"					:"OK",
	"Robot Battery getLastError"				:"All good; No errors!",
	"Robot Battery getErrorCount"				:"0",
	"Robot Battery getVoltage"					:"3.94V",
	"Robot Battery getCharge"					:"40%",
	"Robot Battery getCurrent"					:"0.55A",
	"Robot Battery getPower"					:"1.05W",
	"Robot Battery getCapacity"					:"1038mAh",
	"Robot Battery isCharging"					:"True",
	"Robot Sensor clearErrors"					:"OK",
	"Robot Sensor getLastError"					:"All good; No errors!",
	"Robot Sensor getErrorCount"				:"0",
	"Robot Sensor getTemperature"				:"20.37C",
	"Robot Sensor getPressure"					:"101.35 kPa",
	"Robot Sensor getHumidity"					:"40.83%",
	"Robot System restart"						:"OK",
	"Robot System getAvailableMemory"			:"3452",
	"Robot System getVersion"					:"V1.1",
	"Robot System ping"							:"pong",
}
